---
offsitebuddy_client_root: /etc/offsitebuddy/jobs
offsitebuddy_restic_image: restic/restic:0.19.0
offsitebuddy_client_jobs: []
offsitebuddy_start_services: true
offsitebuddy_backup_randomized_delay_sec: 1800
offsitebuddy_cleanup_stale: false
offsitebuddy_manage_systemd: true
offsitebuddy_client_owner: root
offsitebuddy_client_group: root
