---
dependency:
  name: galaxy
  options:
    requirements-file: requirements-dev.yml
driver:
  name: docker
platforms:
  - name: offsitebuddy-instance
    image: geerlingguy/docker-debian12-ansible:latest
    command: /sbin/init
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
verifier:
  name: ansible
