---
dependency:
  name: galaxy
  options:
    requirements-file: requirements-dev.yml
driver:
  name: docker
platforms:
  - name: offsitebuddy-instance
    image: debian:12
    command: /sbin/init
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
