---
dependency:
  name: galaxy
  options:
    requirements-file: requirements-dev.yml
driver:
  name: docker
platforms:
  - name: offsitebuddy-instance
    image: geerlingguy/docker-debian12-ansible:latest
    command: sleep infinity
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
verifier:
  name: ansible
scenario:
  converge_sequence:
    - create
    - converge
  verify_sequence:
    - verify
