---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install passlib for htpasswd module
      ansible.builtin.apt:
        name: python3-passlib
        state: present
        update_cache: true
