---
- name: Validate configured quota paths
  ansible.builtin.include_role:
    name: itsomidkarami.offsitebuddy.quota
  vars:
    offsitebuddy_quota_items: >-
      {{ offsitebuddy_friends | map(attribute='quota') | list }}
