---
- name: Run initial backup
  vars:
    job_dir: "{{ offsitebuddy_client_root }}/{{ job.name }}"
    marker_file: "{{ job_dir }}/.initial-backup-complete"
  ansible.builtin.command:
    argv:
      - "{{ job_dir }}/backup.sh"
    creates: "{{ marker_file }}"
  no_log: true

- name: Mark successful initial backup
  ansible.builtin.file:
    path: >-
      {{ offsitebuddy_client_root }}/{{ job.name }}/.initial-backup-complete
    state: touch
    mode: "0644"
    access_time: preserve
    modification_time: preserve
  no_log: true
